// <auto-generated />
namespace HouseStarkBlog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class PostVisitsCounter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostVisitsCounter));
        
        string IMigrationMetadata.Id
        {
            get { return "201412071747414_PostVisitsCounter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
